### PR TITLE
Added bumpfire spade grip

### PR DESCRIPTION
**Pull request by T-Kyouko**
Uploaded bumpfire spade grip stls

### CODE REVIEW

**Comment by maduce** [comment]
@T-Kyouko What gun is this for?

 Do you have STEP or IGES files for it? if not do you have SLDRT, F3d, FCStd, prt or IPT files for it?

**Comment by T-Kyouko** [comment]
@maduce Its for an AR with a milspec 6po buffer; I'll specify in the readme.

I'll upload IGES and FCStd files and reorganize.

**Comment by T-Kyouko** [comment]
@maduce 

Done. See new commits.

**Comment by T-Kyouko** [comment]
@maduce can this be merged?

**Comment by maduce** [comment]
Sorry for long wait. Merged.

**Pull request merged**
